---

- name: Create a VIP, pool and pool members
  hosts: big-ip
  connection: local

  vars:
    provider:
      password: bebasmas6868
      server: 10.1.0.246
      user: root
      validate_certs: no
      server_port: 443

  tasks:
    - name: Create a pool
      bigip_pool:
        provider: "{{ provider }}"
        lb_method: ratio-member
        name: web
        slow_ramp_time: 120
      delegate_to: localhost

    - name: Add members to pool
      bigip_pool_member:
        provider: "{{ provider }}"
        description: "webserver {{ item.name }}"
        host: "{{ item.host }}"
        name: "{{ item.name }}"
        pool: web
        port: 80
      with_items:
        - host: 10.1.2.51
          name: web01
        - host: 10.1.2.52
          name: web02
      delegate_to: localhost

    - name: Create a VIP
      bigip_virtual_server:
        provider: "{{ provider }}"
        description: foo-vip
        destination: 10.1.1.246
        name: vip-1
        pool: web
        port: 80
        snat: Automap
        profiles:
          - http
          - websecurity
      delegate_to: localhost

  
#buat bikin asm
    - name: Create asm-1 ASM policy and activate
      bigip_asm_policy:
        name: asm-1
        active: yes
        state: present
        provider: "{{ provider }}"
      delegate_to: localhost

    - name: Create policies
      bigip_policy:
        name: vip-1
        state: present
        provider: "{{ provider }}"     
      delegate_to: localhost

#buat create local policies draft
    - name: create policy
      bigip_policy_rule:
        policy: vip-1
        name: manual
        actions:
          - type: enable 
            asm_policy: asm-1
        conditions:
          - type: all_traffic
        provider: "{{ provider }}" 
      delegate_to: localhost

    - name: Apply vip setelah draft di save
      bigip_virtual_server:
        provider: "{{ provider }}"
        description: foo-vip
        destination: 10.1.1.246
        name: vip-1
        pool: web
        port: 80
        snat: Automap
        profiles:
          - http
          - websecurity
        policies:
          - vip-1
      delegate_to: localhost
